### ISSUE TITLE
Network.paymentsByTransaction(txnHash: String)

### ISSUE THREAD

**Issue by Synesso** [Synesso/scala-stellar-sdk#10]
As per `Network.payments`, but filtered by transaction hash to match https://www.stellar.org/developers/horizon/reference/endpoints/payments-for-transaction.html

**Comment by cmichi** [comment]
I think this issue is already implemented in `master` and can be closed: https://github.com/Synesso/scala-stellar-sdk/blob/master/src/main/scala/stellar/sdk/Network.scala#L197-L206.
