### ISSUE TITLE
Unsealed traits in Horizon ADT prevents many shapless-based derivators to derive instances correctly

### ISSUE THREAD

**Issue by ivan71kmayshan27** [Synesso/scala-stellar-sdk#64]
There is handy JSON scala library with codecs-derivation called circe. It uses labeled generic from shapeless to derive instances, but labeled generic itself supports only sealed trait families. 

I found some unsealed traits in ADT, which prevent circe from working. For example, trait `stellar.sdk.model.op.Operation` is unsealed, and contains many subtypes, so to serialize this trait, boilerplate should be used: 
```
  implicit val operationEncoder: Encoder[Operation] = {
    case o: AccountMergeOperation => o.asJson
    case o: AllowTrustOperation => o.asJson
    case o: BumpSequenceOperation => o.asJson
    case o: ChangeTrustOperation => o.asJson
    case o: CreateAccountOperation => o.asJson
    case o: ManageDataOperation => o.asJson
    case o: ManageOfferOperation => o.asJson
    case o: InflationOperation => o.asJson
    case o: PathPaymentOperation => o.asJson
    case o: CreatePassiveOfferOperation => o.asJson
    case o: SetOptionsOperation => o.asJson
  }
```
There are also `NonNativeAsset` trait in assets that could be made sealed just by adding word sealed without any side effects. 

If all the traits were closed, it would be enough to make instances only for Java classes, everything else would be done by circe for us.

I would like to discuss how this can be done.

**Comment by Synesso** [comment]
@ivan71kmayshan27 Please try v0.6.1 & let me know if it's fixed.

**Comment by ivan71kmayshan27** [comment]
@Synesso by the far, everything I tried to encode works well, without boilerplate at all. I`ve briefly checked response types in `stellar.sdk.Network` they seem to be sealed.
