### ISSUE TITLE
Usage of doubles to represent countable variables in LedgerResponse . 

### ISSUE THREAD

**Issue by ivan71kmayshan27** [Synesso/scala-stellar-sdk#72]
Class `stellar.sdk.model.response.LedgerResponse` has fields `totalCoins: Double, feePool: Double`. they used to represent value measured in **Stroops** (1E-7 Lumen). `Double` representation of such an asset makes the conversion of it to `Long`-measured things unsound and potentially unsafe. Please consider introducing either some special wrapper over the `Long`(i.e. `case class Stroop(val value: long) extends AnyVal` ) value or bare Long value instead of Double to fixs this inconsistency.

**Comment by Synesso** [comment]
Thank you. To be consistent, the type for this will be NativeAmount
<https://synesso.github.io/scala-stellar-sdk/api/stellar/sdk/model/NativeAmount.html>.
I'll patch it this weekend.

**Comment by Synesso** [comment]
@ivan71kmayshan27 Please take a look at `v0.6.3` & let me know if it solves your issue. 

Thanks for your ongoing bug reports. It would be great to hear from you about what you are using the SDK for.

**Comment by ivan71kmayshan27** [comment]
Yep, it solves the issue, but I`ve found the same thing in EffectTrustLineCreated and EffectTrustLineUpdated: `limit: Double`, but probably this will be a bit trickier because I see no straightforward way to convert it to NonNativeAmount without issuer info. 

Unfortunately, due to my NDA i can`t say for what I`m using Your library, but I can say that it saves me a lot of time and helps very much.

**Comment by Synesso** [comment]
That's good to hear. If you ever release what you're working on, I'd love to hear about it.

I've just pushed v0.6.4 with changes to `EffectTrustLineCreated`/`Updated` to avoid the rounding issues. It might take a few hours to sync with maven central. LMK how you go with that.

**Comment by ivan71kmayshan27** [comment]
Sorry for dropping off. Everything is nice now.
