### ISSUE TITLE
Horizon v0.18.0 Compatibility

### ISSUE THREAD

**Issue by theaeolianmachine** [Synesso/scala-stellar-sdk#78]
With Horizon v0.18.0, the following breaking changes will occur:

- The `manage_offer` endpoint will be renamed to `manage_sell_offer`
- The `create_passive_offer` endpoint will be renamed to `create_passive_sell_offer`.

We suggest for all Stellar SDK maintainers to offer compatibility between `v.0.17.X` type names as well as the new names in `v.0.18.0` in order to make the transition process from `v0.17.X` to `v0.18.0` to go smoother.

Let me know if you have any questions!

**Comment by Synesso** [comment]
@theaeolianmachine I unfamiliar with these endpoints. Do you mean the `type` field in the operation response JSON document?

**Comment by theaeolianmachine** [comment]
That's correct! Sorry for the mistake from copy pasting this around. If you're using the `type_i` field instead, you shouldn't have anything to migrate (given that the value has not changed, just the name in the `type` field.

**Comment by Synesso** [comment]
Thanks Johnny.
