### ISSUE TITLE
Throw reasonable exception on "Rate Limit exceded" horizon respoce. 

### ISSUE THREAD

**Issue by ivan71kmayshan27** [Synesso/scala-stellar-sdk#86]
When one tries to ask public or another horizon too fast, he gets answer 429 Rate limit exceded. In this sdk we get `MappingException("unknown error", e)`. It would nice to have some kind of exception that indicates that specific response to divide parse issues and rate limit issues.

**Comment by Synesso** [comment]
Thanks again. This is fixed on master. No release yet. Let me know if you need one.
